companies:
  - name: 影视飓风
    domain: mediastorm.jobs.feishu.cn
    type: feishu
    enabled: true

  - name: 字节跳动
    domain: jobs.bytedance.com
    type: bytedance
    enabled: true

  - name: 腾讯
    domain: join.qq.com
    type: tencent
    enabled: true
